#!/bin/bash

# chromosome fasta files and variation VCFs
rs_fasta_prefix=
rs_fasta_suffix=
ens_var_prefix=
ens_var_suffix=

vep_cache_dir=
vep_cache=merged

hive_root_dir=

# location for files generated by pipeline
pipeline_base_dir=

pipeline_host=
pipeline_user=
pipeline_port=

lsf_queue=

# location of the software
vep_dir=/nfs/panda/ensemblgenomes/wormbase/personal/mqt/applications/ensembl-vep

init_pipeline.pl HumanVep::HumanVep_conf -rs_fasta_prefix $rs_fasta_prefix -rs_fasta_suffix $rs_fasta_suffix -ens_var_prefix $ens_var_prefix -ens_var_suffix $ens_var_suffix -vep_cache_dir $vep_cache_dir -vep_cache $vep_cache -hive_root_dir $hive_root_dir -pipeline_base_dir $pipeline_base_dir -piepline_host $pipeline_host -pipeline_user $pipeline_user -pipeline_port $pipeline_port -lsf_queue $lsf_queue -vep_dir $vep_dir -password $1
